### PR TITLE
Fixes - Panic when the corresponding hpa resource is deleted - Issue #19

### PR DESCRIPTION
**Pull request by vnandha**
Tested locally

```
[user@scheduled-scaler-744d9fc4c-p7hk4 /]# ./k8s-restdev-scaling
W0518 09:45:42.426597     100 client_config.go:529] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
E0518 09:45:42.445961     100 scaling-controller.go:95] FAILED TO UPDATE HPA: procs - horizontalpodautoscalers.autoscaling "procs" not found
I0518 09:45:42.446010     100 scaling-controller.go:131] SCHEDULED SCALER CREATED: procs -> procs
E0518 09:46:00.009646     100 scaling-controller.go:107] FAILED TO UPDATE HPA: procs - horizontalpodautoscalers.autoscaling "procs" not found
```

### CODE REVIEW

**Comment by vnandha** [comment]
@ericuldall @m0rganic @ericuldall Could some of you please view this and if you like it can you merge and release the same?

**Comment by ericuldall** [comment]
Hey @vnandha! Thanks for the contribution. I'll review this when I have time this week and get it merged.

**Comment by ericuldall** [comment]
I've tested the code and it seems to work as expected. I will begin prep for release.

**Comment by ericuldall** [comment]
@all-contributors please add @vnandha for bug and maintenance

**Pull request merged**
