### PR TITLE
Add helm & rbac

### PR DESCRIPTION
**Pull request by so0k**
First off, I Love this approach - thanks a lot for making this public. It allows us to define scheduled scaling in a very concise and uniform manner for all our k8s deployments.

in this PR, I simplify deployment a bit by adding a chart for usage with https://helm.sh/ and defined required RBAC permissions as well.

- Currently using a public repo on my organisation's Quay.io account - you'd have to change it when you set up CI/CD for your controller
- I tested on our 1.7 clusters

Also, I think you might want to switch to a Makefile instead

### CODE REVIEW

**Comment by ericuldall** [comment]
Thanks for the PR! I will review this when I have some time. I have thought about starting to host a public image of the latest builds, so I will definitely be coming up with a version structure and starting to host images on DockerHub soon (that should make it easier for people that want to consume the image without doing the build).

I'm interested in the Makefile idea...Do you mean adding one to handle building the bin file?

**Review by ericuldall — CHANGES_REQUESTED** [review]
@so0k Would you please update the repo to use the official image i've created.

`k8srestdev/scaling:latest`

Other than that it looks good to merge once the change is made. Thanks again!

**Comment by so0k** [comment]
@ericuldall - thanks for review - done

not sure how you want to review the conflict on README?

**Review by ericuldall — APPROVED** [review]

**Comment by ericuldall** [comment]
Thanks @so0k ! I think I've found a suitable state for the README. We'll go with it for now and can open a new feature if we desire any changes to the README later.

**Review by ericuldall — APPROVED** [review]

**Comment by ericuldall** [comment]
@all-contributors please add @so0k for infra and doc

**Pull request merged**
