### PR TITLE
If updating HPA fails due to conflict, try again

### LINKED ISSUE #28: If a schedule fires right when HPA is updating, the change is missed
It doesn't happen very often, but because the code at https://github.com/West-Coast-Devops/scheduled-scaler/blob/master/scaling-controller.go#L133-L143 does

- Get hpa from k8s
- Change hpa (in memory)
- Update hpa ih k8s

and because every 15s the HPA updates the status from any queried metrics, there is a chance for collision.

It should retry, if possible, at least once - chances of getting hit with the next 15s HPA update are slim, so this would most likely fix it.  If it's possible to know the error is because it was updated, then retry until the error is nil or something else

### PR DESCRIPTION
**Pull request by scr-oath**
This is a common concurrency case - when doing get, update, put on a resource
which may be updated elsewhere, one has to either use synchronization mechanisms
or retry.

I don't believe that k8s has a synchronization mechanism to prevent against
the HPA metrics checking from updating the status at exactly the same time
that ss is trying to update the min/max replicas.

Since this new code is retrying, there _is_ a risk in colliding with another
ss cron entry as well, and there _are_ synchronization mechanisms (mutex)
to help ensure that the currently scheduling thing (which got there first)
gets to retry, before the new one comes in.

Fixes #28.

### CODE REVIEW

**Comment by scr-oath** [comment]
The bulk of this change is from mockgen to create the myriad of mocks required to test the `scheduledScalerHpaCronAdd` function.

Should you need to update, these were generated using
```bash
go generate ./...
```

**Comment by scr-oath** [comment]
@ericuldall - can you take a look at this one as well? It's a little more exhaustive than the last one (to add mocks for a unit test) but any panic can cause issues with the CRD, so removing them, also fixes #24 as well.

- Fixes #24 
- Fixes #28 

If there's any chance you'd be able to hook up https://travis-ci.org/ for this to at least run tests, that would be helpful 😄

**Comment by ericuldall** [comment]
> @ericuldall - can you take a look at this one as well? It's a little more exhaustive than the last one (to add mocks for a unit test) but any panic can cause issues with the CRD, so removing them, also fixes #24 as well.
> 
> * Fixes #24
> * Fixes #28
> 
> If there's any chance you'd be able to hook up https://travis-ci.org/ for this to at least run tests, that would be helpful 😄

I'll create a new issue to get CI running the tests.

Also, what do you think about making that retry number configurable? I'm thinking at the very least it should be globally configurable at the scheduled scaler controller but there may be value in allowing each scheduled scaler definition to have a custom retry configuration based on how important it is to the end user. Thoughts?

**Comment by scr-oath** [comment]
That makes sense; I'm thinking for HPA, you only need 1 retry as HPA only fires every 15s the chances and observed collisions are very rare, but we _have_ seen them.  I can make the config default to 1 retry and be settable at least for the controller as you say - we can add configurability by customers as a feature later on

**Pull request merged**
