### PR TITLE
Upgrade cron to support timezones.

### LINKED ISSUE #30: Upgrade the cron version so that timezone may be specified
Newer versions of https://github.com/robfig/cron support TZ and CRON_TZ entries a la environment variables to be prepended to the spec string. This is a very useful feature some of our apps would love to use.

### PR DESCRIPTION
**Pull request by scr-oath**
Fixes #30

### CODE REVIEW

**Comment by ericuldall** [comment]
@scr-oath timeZone was supported before. Was it not working or is this addition doing something new?

**Comment by scr-oath** [comment]
I think this stems from confusion from reading documentation on the current version of robfig/cron which has split the timezone of a cron apart from the timezone of a schedule spec. Perhaps we should discuss a bit more to understand the diffs and potential impact.

The one currently in use (v1) instantiates a cron object with a timezone uses that timezone to calculate the "now" and look for the next time from the spec (which does _NOT_ have a time zone).

The new one (v3) has a timezone for the cron as before, and also allows a timezone in the schedule spec - when not specified it defaults to LocalTime and does not perform any transform on the given time, but when specified applies the appropriate shift to get to "absolute Time".

So… it would seem that, with the newer robfig/cron, one as two separate mechanisms to play with depending on how they'd like to operate - either set the ss timezone and have all cron entries use that, or don't (or set to UTC; the timezone of the node/pod) and have each schedule spec make its own decision.  To me that sounds awkward, but if there's a known event - who knows, say the start of Carnival in Rio de Janeiro that you want to scale for, you could do that by picking its timezone for that specific spec.

**Comment by scr-oath** [comment]
So… I guess having a really old robfig/cron is a disservice to anyone who might look for documentation on how it works - would be nice to just modernize that dependency.

**Comment by scr-oath** [comment]
Abandoning for now - will bring up again if the per-spec timezone is really needed

**Pull request closed without merging**
