### PR TITLE
Fix the test by including both the test file and the file under test

### PR DESCRIPTION
**Pull request by scr-oath**
https://stackoverflow.com/questions/31352239/how-to-test-the-main-package-functions-in-golang

### CODE REVIEW

**Comment by ericuldall** [comment]
Seems closer but still failing in Travis.

**Comment by scr-oath** [comment]
Yes, because of the fake class being bogus - needs to be removed - I can fix that here…

**Comment by scr-oath** [comment]
Yay… 🟢 Build passed :D

**Comment by ericuldall** [comment]
cool. I'll merge to #34

**Pull request merged**
